version: '2'

services:

  pokemonstoragesystem:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pokemonstoragesystem_dev
    volumes:
      - .:/data
      - ./certs:/root/.mitmproxy
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "1"
    ports:
      - 9000:80
      - 8081:8080

